### ISSUE TITLE
Only one story per user supported?

### ISSUE THREAD

**Issue by marcelo-tm** [ue/react-native-story#2]
Is it possible to have multiple stories per user?

**Comment by tmjordan** [comment]
It will be nice

**Comment by hirbod** [comment]
+1

**Comment by ue** [comment]
Thank you for the additional issue, I will work that with video support for new release

**Comment by SmhDmn** [comment]
> Thank you for the additional issue, I will work that with video support for new release

@ue I'm looking forward to this ,  when will you planning to do it ?

**Comment by Nuneshere** [comment]
@SmhDmn seems like never ahhaa, do you have any work arounds?

**Comment by marcelo-tm** [comment]
> @SmhDmn seems like never ahhaa, do you have any work arounds?

I don't, I'm using flutter for a while now.
